### PR TITLE
Workaround for the scrollable tabstrip issue

### PR DESCRIPTION
**Pull request by hugo-caires**
This workaround should solve the issues #38 and #35. This has been driving me crazy as I usually have a huge amount of tabs opened, so every time I opened a new tab, I had to scroll all the way from the end of the tabs bar to wherever the new tab was opened.
What it does is: once the new tab is moved, activate the opener tab (the tab that originated the new tab) and then activate the new tab once again. This forces the browser to update the tabs bar scrolling.
There might be an issue if the `tab.openerTabId` is not available though.

### CODE REVIEW

**Comment by ArnaudLigny** [comment]
Thanks a lot @hugo-caires 👍

**Comment by asampal** [comment]
I can hardly wait! As with @hugo-caires, the behavior reported by @hugo-caires is a huge pain for me, as well.

**Comment by asampal** [comment]
@ArnaudLigny will you get this new version posted to the stores soon? I installed from the release archive, but Edge keeps prompting me about removing developer mode extensions.

**Comment by ArnaudLigny** [comment]
@asampal the release 0.4.6 is already available on [Chrome store](https://chromewebstore.google.com/detail/open-new-tab-after-curren/mmcgnaachjapbbchcpjihhgjhpfcnoan), but I'm waiting too for Edge... :-/

image

**Comment by asampal** [comment]
Is there any significant difference between the Chrome and the Edge extensions? If there isn't, I could just install from the Chrome site.

**Comment by ArnaudLigny** [comment]
>Is there any significant difference between the Chrome and the Edge extensions? If there isn't, I could just install from the Chrome site.

Absolutely no differences :-)

**Pull request merged**
